name: Copy PR Templates

on:
  workflow_run:
    workflows: ["Copy PR Templates"]  # Name of the workflow in your PR templates repository

jobs:
  copy-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run workflow from PR templates repository
        run: |
          cp -r $GITHUB_WORKSPACE/pr-templates/* .github/PULL_REQUEST_TEMPLATE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
