name: Workflow B

on:
  repository_dispatch:
    types:
      - workflow-b-event

jobs:
  workflow-b:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run workflow from PR templates repository
        run: |
          cp -r $GITHUB_WORKSPACE/pr-templates/* .github/PULL_REQUEST_TEMPLATE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
